name: Web UI-Build, Test & Publish Docker
on:
  push:

env:
  IMAGE_NAME: web-ui

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose build test

      - name: Build image
        run: docker-compose build release

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GPR_USER }}
          # Cannot use GITHUB_TOKEN to push to GHCR
          password: ${{ secrets.GPR_PAT }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix (refs/heads/ or refs/tags/) from version
          # but keep the rest of the ref. Replaces / with - to make the package name valid.
          # Do not attempt to obtain the version number from vx.y.z tags:
          # this is handled by the publish_version workflow.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,refs/\(heads\|tags\)/\(.*\),\2,' | tr '/' '-')
          # Always tag with git sha or version tag
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          # Use Docker `latest` tag convention for default branch.
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Apply staging configuration
        run: cp -r .override-staging/ .override/

      - name: Build image
        run: docker-compose build release

      - name: Push image (staging)
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix (refs/heads/ or refs/tags/) from version
          # but keep the rest of the ref. Replaces / with - to make the package name valid.
          # Do not attempt to obtain the version number from vx.y.z tags:
          # this is handled by the publish_version workflow.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,refs/\(heads\|tags\)/\(.*\),\2,' | tr '/' '-')
          VERSION=$VERSION-staging
          # Always tag with git sha or version tag
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
